# -*- coding: utf-8 -*-
"""Watermarks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10EGs1w4Z6i2hPMzMbNS5TPXo7B8Yev5V
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Watermarks/"
!ls

import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

base_dir = 'watermarks'
train_dir = os.path.join(base_dir,'train')
test_dir = os.path.join(base_dir, 'test')

# Cargar imágenes con redimensionamiento
target_size = (100, 100)
train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=target_size,
    batch_size=20,
    class_mode='binary')

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=target_size,
    batch_size=20,
    class_mode='binary')